#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi

if type "java" > /dev/null 2>&1; then
    echo "java is exist"
else
    apt-get update 
    apt-get install -y openjdk-11-jdk
    apt-get -y autoremove 
    apt-get clean 
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
fi